Cloud_CMDB/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from cmdbServer import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index),
    url(r'^accounts/login/',views.account_login),
    url(r'^accounts/logout/',views.account_logout),
    url(r'^api/',include('cmdbApi.urls')),
    url(r'^asset/',include('cmdbServer.urls')),
]

cmdbApi/urls.py
# -*- coding:utf-8-*-

from django.conf.urls import url,include
from rest_framework.urlpatterns import format_suffix_patterns
from cmdbApi import views


urlpatterns = format_suffix_patterns([
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^idc/$',views.IdcList.as_view(),name='idc-list'),
    url(r'^idc/(?P<pk>[0-9]+)/$',views.IdcDetail.as_view(),name='idc-detail'),
    url(r'^cabint/$',views.CabintList.as_view(),name='cabint-list'),
    url(r'^cabint/(?P<pk>[0-9]+)/$',views.CabintDetail.as_view(),name='cabint-detail'),
    url(r'^server/$',views.ServerList.as_view(),name='server-list'),
    url(r'^server/(?P<pk>[0-9]+)/$', views.ServerDetail.as_view(), name='servers-detail'),
    url(r'^group/$',views.GroupList.as_view(),name='group-list'),
    url(r'^group/(?P<pk>[0-9]+)/$',views.GroupDetail.as_view(),name='group-detail'),
    url(r'^company/$',views.CompanyList.as_view(),name='company-list'),
    url(r'^company/(?P<pk>[0-9]+)/$',views.CompanyDetail.as_view(),name='company-detail'),
    url(r'^warranty/$',views.warrantyList.as_view(),name='warranty-list'),
    url(r'^warranty/(?P<pk>[0-9]+)/$',views.warrantyDetail.as_view(),name='warranty-detail'),
    url(r'^nic/$',views.NicList.as_view(),name='nic-list'),
    url(r'^nic/(?P<pk>[0-9]+)/$',views.NicDetail.as_view(),name='nic-detail'),
    url(r'^bonding/$',views.BondingList.as_view(),name='bonding-list'),
    url(r'^bonding/(?P<pk>[0-9]+)/$',views.BondingDetail.as_view(),name='bonding-detail'),
    url(r'^ram/$',views.RamList.as_view(),name='ram-list'),
    url(r'^ram/(?P<pk>[0-9]+)/$',views.RamDetail.as_view(),name='ram-detail'),
    url(r'^disk/$',views.DiskList.as_view(),name='disk-list'),
    url(r'^disk/(?P<pk>[0-9]+)/$',views.DiskDetail.as_view(),name='disk-detail'),
    url(r'^cpu/$',views.CpuList.as_view(),name='cpu-list'),
    url(r'^cpu/(?P<pk>[0-9]+)/$',views.CpuDetail.as_view(),name='cpu-detail'),
    url(r'^device/$',views.DeviceList.as_view(),name='device-list'),
    url(r'^device/(?P<pk>[0-9]+)/$',views.DeviceDetail.as_view(),name='device-detail'),
    url(r'^protocol/$',views.ProtocolList.as_view(),name='protocol-list'),
    url(r'^protocol/(?P<pk>[0-9]+)/$',views.ProtocolDetail.as_view(),name='protocol-detail'),
    url(r'^apps/$', views.AppsList.as_view(), name='apps-list'),
    url(r'^apps/(?P<pk>[0-9]+)/$',views.AppsDetail.as_view(), name='apps-detail'),
    url(r'^monitor/$', views.MonitorList.as_view(), name='monitor-list'),
    url(r'^monitor/(?P<pk>[0-9]+)/$',views.MonitorDetail.as_view(), name='monitor-detail'),

    # url(r'^gfw/$',views.GFWList.as_view(),name='gfw-list'),
    # url(r'^gfw/(?P<pk>[0-9]+)/$',views.GFWDetail.as_view(),name='gfw-detail'),

    # url(r'^task/$',views.TaskList.as_view(),name='task-list'),
    # url(r'^task/(?P<pk>[0-9]+)/$',views.TaskDetail.as_view(),name='task-detail'),

])

cmdbServer/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator,MaxLengthValidator
from django.contrib.postgres.fields import JSONField
from django.contrib.auth.models import User
from cmdbServer.core.model_func import savelog

# Create your models here.


device_status = (
    (0,'已启用'),
    (1,'未启用'),
    (2,'故障'),
    (3,'下线'),
)

approver_status = (
    (0,'待审批'),
    (1,'已审批'),
    (2,'待协商'),
)

location= ((x,x) for x in range(1,43))

class IDC(models.Model):
    name = models.CharField(verbose_name='机房名称', max_length=200, unique=True)
    address = models.CharField(verbose_name='机房地址', max_length=200)
    contacts = models.CharField(verbose_name='机房联系组', max_length=32, blank=True, null=True)
    phone = models.CharField(verbose_name='联系电话', max_length=12, blank=True, null=True)
    remarks = models.CharField(verbose_name='备注', max_length=200, blank=True, null=True)

    class Meta:
        verbose_name = '机房信息'
        verbose_name_plural = '机房信息'

    def __str__(self):
        return self.name

class Cabint(models.Model):
    number = models.CharField(verbose_name='编号',max_length=32,blank=True,null=True)
    size = models.IntegerField(verbose_name='容量')
    useposition = models.SlugField(verbose_name='已用高度',default=0,blank=True)
    room_number = models.CharField(verbose_name='机房编号',max_length=32,blank=True,null=True)
    idc = models.ForeignKey(IDC,on_delete=models.CASCADE,related_name='cabintd')

    class Meta:
        verbose_name = '机柜'
        verbose_name_plural = '机柜'
        unique_together = ("number",'room_number','idc')

    def __str__(self):
        return "%s,%s" %(self.idc,self.number)

    @property
    def idc_name(self):
        return "%s" % (self.idc.name)

class Warranty(models.Model):
    company = models.CharField(verbose_name='质保商',max_length=200,unique=True)
    start_date = models.DateTimeField(verbose_name='质保起始时间')
    end_date = models.DateTimeField(verbose_name='质保结束时间')

    class Meta:
        verbose_name = '质保信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return "%s" %(self.end_date)


class Company(models.Model):
    device_types = (
        (0,'服务器'),
        (1,'网络设备'),
        (2,'CPU'),
        (3,'内存'),
        (4,'硬盘'),
    )
    id = models.AutoField(primary_key=True)
    name = models.CharField(verbose_name='厂商', max_length=64, blank=True, null=True,)
    model = models.CharField(verbose_name='型号', max_length=64, blank=True, null=True,unique=True)
    types = models.SmallIntegerField(verbose_name="设备类型",choices=device_types,default=0)
    height = models.IntegerField(verbose_name='设备高度',blank=True,null=True,validators=[MaxValueValidator(42),
                                                                             MinValueValidator(1)])
    class Meta:
        verbose_name = '厂商'
        verbose_name_plural = '厂商'

    def __str__(self):
        return "%s,%s,%s" %(self.name,self.model,self.get_types_display())

class Group(models.Model):
    name = models.CharField(verbose_name='组',max_length=32,unique=True)

    class Meta:
        verbose_name = "设备组"
        verbose_name_plural = verbose_name

    def __str__(self):
        return "%s" %self.name

class Device(models.Model):
    device_types = (
        (0,'交换机'),
        (1,'路由器'),
        (2,'防火墙'),
        (3,'IDS/IPS'),
        (4,'WAF'),
        (5,'DDOS防火墙'),
    )
    id = models.AutoField(primary_key=True)
    sn = models.CharField(max_length=32, blank=True, null=True, unique=True)
    name = models.CharField(max_length=32,unique=True)
    types = models.SmallIntegerField(verbose_name='设备类型', choices=device_types, default=0)
    company = models.ForeignKey(Company,verbose_name='型号',related_name='devices', on_delete=models.CASCADE,)
    ipaddress = models.GenericIPAddressField(unique=True,verbose_name='IP地址')
    cabint = models.ForeignKey(Cabint, verbose_name='机柜', related_name='devices', on_delete=models.CASCADE,blank=True,null=True)
    position = models.IntegerField(verbose_name='机柜位置', default=1, blank=True, null=True,unique=True,
                                   validators=[MaxValueValidator(42),
                                               MinValueValidator(1)])
    device_statuses = models.SmallIntegerField(choices=device_status, default=0,verbose_name='设备状态')
    group = models.ForeignKey(Group,related_name='device', on_delete=models.CASCADE, verbose_name='设备组', blank=True,
                              null=True)
    start_date = models.DateTimeField(verbose_name='上线时间',auto_now_add=True)
    end_date = models.DateTimeField(verbose_name='下线时间',blank=True, null=True)
    warranty = models.ForeignKey(Warranty,verbose_name='质保时间', related_name='device', on_delete=models.CASCADE, blank=True, null=True)
    contacts = models.CharField(verbose_name='负责人', max_length=32, blank=True, null=True)

    class Meta:
        verbose_name = "网络设备"
        verbose_name_plural = '网络设备'

    def create(self,*args,**kwargs):
        self.save(args,kwargs)

    def save(self, *args, **kwargs):
        objects = Cabint.objects.filter(id=self.cabint_id).values('useposition', 'size')[0]
        useposition = objects['useposition']
        cabint_size = objects['size']
        if not useposition:
            useposition = 0
        useposition = int(useposition)
        if self.company.height is None:
            self.company.height = 0
        height = int(self.company.height)
        if height + useposition < cabint_size:
            useposition += height
            if not self.id:
                super(self.__class__, self).save(*args, **kwargs)
                Cabint.objects.filter(id=self.cabint_id).update(useposition=useposition)
            super(self.__class__, self).save(*args, **kwargs)

        return MaxLengthValidator(cabint_size)

    def delete(self, using=None, keep_parents=False):
        objects = Cabint.objects.filter(id=self.cabint_id).values('useposition')[0]
        useposition = int(objects['useposition']) - int(self.company.height)
        if useposition < 0: useposition = 0
        Cabint.objects.filter(id=self.cabint_id).update(useposition=useposition)

        super(self.__class__, self).delete()

    def __str__(self):
        return "%s,%s" %(self.get_types_display(),self.ipaddress,)

    @property
    def group_name(self):
        return self.group.name

    @property
    def company_name(self):
        return "%s,%s" % (self.company.name, self.company.model)

class Protocol(models.Model):
    protocols = (
        (0,'VLAN'),
        (1,'TRUNK'),
        (2,'RIP'),
        (3,'OSPF'),
        (4,'IBGP'),
        (5,'EBGP'),
        (6,'BIND'),
    )
    name = models.SmallIntegerField(verbose_name='协议类型',choices=protocols,default=0,)
    number = models.CharField(verbose_name='协议号',max_length=8,default='VLAN1')
    ipaddress = models.GenericIPAddressField(verbose_name='协议IP',blank=True,null=True)
    port_range = models.CharField(verbose_name='端口范围',max_length=8,default='1-4',)
    device = models.ForeignKey(Device,related_name='protocols',on_delete=models.CASCADE,blank=True,null=True)

    class Meta:
        verbose_name = '协议'
        verbose_name_plural = '协议'

    def __str__(self):
        return "%s,%s" %(self.device,self.number,)

class Servers(models.Model):
    servers_type = (
        (0, '机架'),
        (1, '塔式'),
        (2, '小型机'),
        (3, '刀片'),
    )
    sn = models.CharField(max_length=32, blank=True, null=True, unique=True)
    company = models.ForeignKey(Company,verbose_name='型号',related_name='servers', on_delete=models.CASCADE,blank=True,null=True,)
    types = models.SmallIntegerField(verbose_name='服务器类型', choices=servers_type,default=0,)
    cabint = models.ForeignKey(Cabint,verbose_name='机柜',related_name='servers',on_delete=models.CASCADE,blank=True,null=True)
    position = models.IntegerField(verbose_name='机柜位置',blank=True,null=True,validators=[MaxValueValidator(42),
                                               MinValueValidator(1)])
    hostname = models.CharField(verbose_name='主机名', max_length=64, unique=True)
    ipaddress = models.GenericIPAddressField(verbose_name='管理地址',unique=True)
    vlan = models.ForeignKey(Protocol,verbose_name='管理VLAN',blank=True,related_name='servers', on_delete=models.CASCADE)
    system = models.CharField(verbose_name='操作系统', max_length=32, blank=True, null=True)
    version = models.CharField(verbose_name='系统版本号', max_length=32, blank=True, null=True)
    use_status = models.SmallIntegerField(verbose_name='使用状态',choices=device_status,default=0)
    conn_status = models.CharField(verbose_name='连接状态',max_length=32,blank=True,null=True)
    group = models.ForeignKey(Group,verbose_name='服务器组',blank=True,null=True,related_name='servers', on_delete=models.CASCADE,)
    start_date = models.DateTimeField(verbose_name='上线时间', auto_now_add=True)
    end_date = models.DateTimeField(verbose_name='下线时间', blank=True, null=True)
    warranty = models.ForeignKey(Warranty, verbose_name='质保时间', related_name='servers', on_delete=models.CASCADE,
                                 blank=True, null=True)
    user = models.CharField(verbose_name='SSH用户名',max_length=32,blank=True,null=True)
    password = models.CharField(verbose_name='SSH密码',max_length=256,blank=True,null=True)
    port = models.CharField(verbose_name='SSH端口号',max_length=8,blank=True,null=True)
    contacts = models.CharField(verbose_name='负责人', max_length=32, blank=True, null=True)

    class Meta:
        verbose_name = '服务器'
        verbose_name_plural = '服务器'
        unique_together = "cabint","position"


    def save(self, *args, **kwargs):
        objects = Cabint.objects.filter(id=self.cabint_id).values('useposition','size')[0]
        useposition = objects['useposition']
        cabint_size = objects['size']
        if not useposition:
            useposition = 0
        useposition = int(useposition)
        if self.company.height is None:
            self.company.height = 0

templates/gloab-form/add_form.html
{% extends 'bash/bash.html' %}
{% block head%}

{% endblock %}
{% block content %}
{% load deploy_tag %}
<div class="row" id="report1">
    <div class="col-sm-12">
        <ol class="breadcrumb" style="background-color: #ffffff;font-size: 10px;top: -20px">
            <a href="/" class="tip-bottom" data-original-title="Go to Home"><i class="icon-home"></i>Home </a>>
            <a href="/asset/{{ app_name }}/{{ model_name }}/" class="tip-bottom" data-original-title="">{% build_project_name admin_class %}</a>>
            <a href="/asset/{{ app_name }}/{{ model_name }}/ADD{% build_project_name admin_class %}" title="添加{% build_project_name admin_class %}" class="tip-bottom" data-original-title="">添加{% build_project_name admin_class %}</a>
        </ol>
        <h4 style="text-align: center">{% build_project_verbose_name admin_class %}</h4>

    </div>
</div>

<div class="row" id="report1">
    <div class="col-sm-12">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title span10" style="border: 0px solid">
                    <ul class="nav nav-tabs col-sm-1" >
                        <li role="navigation" class="active"><a href="#alert-tab" data-toggle="tab">逐条添加</a></li>
                        <li role="navigation"><a href="#note-tab" data-toggle="tab">批量添加</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="span12" style="width: 90%">
            <div class="widget-box">
                <div id="generalTabContent" class="tab-content responsive">
                    <div id="alert-tab" class="tab-pane fade in active">
                         <form method="post">{% csrf_token %}
                            <div class="modal-body">
                                <div class="modal-body" >
                                     <form class="form-horizontal" method="post">{% csrf_token %}
                                    {% for field in form_obj %}
                                        {% if field.name == 'useposition' %}
                                        {{ pass }}
                                        {% else %}
                                        <div class="form-group ">
                                            <label id="{{ field.name }}" style="width: 9%;font-size: 12px">{{ field.label }}：</label>
                                            {% if field.name == 'phone' %}
                                                <input type="text" name="phone" maxlength="11" oninput="value=value.replace(/[^\d]/g,'')">
                                            {% elif field.name == 'start_date' %}
                                                <input type="date" name="start_date" class="form-control" id="id_start_date">
                                            {% elif field.name == 'end_date' %}
                                                <input type="date" name="end_date"  class="form-control" id="id_end_date">
                                            {% elif field.name == 'size' %}
                                                <input type="number" name="size"  class="form-control" id="id_size">
                                                <span style="color: red">(单位:U)</span>
                                            {% elif field.name == 'password' %}
                                                <input type="password" name="password"  class="form-control" id="id_password">
                                                <span style="color: red" id="password_errors"></span>
                                            {% else %}
                                                {{ field }}
                                            {% endif %}
                                            <span style="color: red" id="{{ field.name }}_errors">{{ field.errors.0 }}  </span>
                                        </div>
                                        <br>
                                        {% endif %}
                                    {% endfor %}
                                     </form>
                                </div>
                                 <div class="form-group">
                                    <div class="span8">
                                        <input type="submit" id="save" class="btn btn-info" value="保存">
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>

                    <div id="note-tab" class="tab-pane fade" >
                        <p>请下载Excel文件, 按照格式填写主机信息, 上传导入. <a href="/asset/{{ app_name }}/{{ model_name }}/download/" style="color: #1a1ad2">点击下载模板</a></p>
                        <p></p>
                        <form id="upfile" action="/asset/{{ app_name }}/{{ model_name }}/upload/" method="post" enctype="multipart/form-data" target="file">
                            <input  type="file" name="upfile" />
                            <input type="submit" value="导入配置" class="btn-success btn btn-sm" >
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>




<script src="/static/js/jquery.js"></script>
<script>

    $(function () {
        $("#upload").click(function () {
            document.getElementById('files').submit();
        })
    })

    $("#id_types").change(function () {
        new_id = $(this).val();
        heigths = document.getElementById('height');
        id_heigths = document.getElementById('id_height');
        if (new_id > 1){
            heigths.style.display='none'
            id_heigths.style.display='none'
        }
        else {
            heigths.style.display='block'
            id_heigths.style.display='block'
        }
    })

    $("#id_size").change(function () {
        var size_errors = document.getElementById('size_errors');
        if (this.value > 48){
            size_errors.innerText = '机柜容量不能大于48U';
            $("#save").attr('disabled',true);
        }else {
            size_errors.style.innerText = ' ';
            $("#save").attr('disabled',false);
        }
    })

</script>
{% endblock %}

templates/gloab-form/change_form.html
{% extends 'bash/bash.html' %}
{% block head%}

{% endblock %}
{% block  content%}
{% load deploy_tag %}
    <div class="row" id="report1">
        <div class="col-sm-12">
            <ol class="breadcrumb" style="background-color: #ffffff;font-size: 10px;top: -20px">
                <a href="/" class="tip-bottom" data-original-title="Go to Home"><i class="icon-home"></i> Home </a>>
                <a href="/asset/{{ model_name }}/" class="tip-bottom" data-original-title="">{% build_project_verbose_name admin_class %}</a>>
                <a href="/asset/{{ model_name }}/" title="数据中心信息表" class="tip-bottom" data-original-title="">{% build_project_verbose_name admin_class %}信息表</a>
            </ol>
            <h4 style="text-align: center">{% build_project_verbose_name admin_class %}</h4>

        </div>
    </div>
    <div class="row" id="report1">

    </div>
<div class="row" id="report1">
    {{ form_obj.errors }}
    <form class="form-horizontal col-md-6" id="forms" method="post">{% csrf_token %}
        {% for field in form_obj %}
            {% if field.name == 'useposition' %}{{ pass }}{% else %}
            <div class="form-group row">
                <label class="col-form-label col-sm-3" for="example-tel-input" >
                    {% if field.field.required %}
                    {{ field.label }}
                    {% else %}
                        <span style="font-weight: normal">{{ field.label }}</span>
                    {% endif %}
                </label>
                <div class="col-9 col-sm-7">
                    {% if field.name in admin_class.readonly_fields %}
                        <div>{% get_readonly_field_val field.name form_obj.instance %} </div>
                    {% else %}
                        {% if field.name in admin_class.filter_horizontal %}
                            <div >
                                {% get_selected_m2m_objects form_obj field.name as selected_m2m_objects %}

                                {% get_m2m_objects admin_class field.name selected_m2m_objects as m2m_objects  %}
                                <div class="col-lg-5">
                                    <input oninput="FuzzySearch(this)" type="search" class="form-control">
                                    <select  id="{{ field.name }}_from"  multiple class="form-control">
                                        {% for obj in m2m_objects %}
                                            <option ondblclick="MoveElementTo(this,'{{ field.name }}_to','{{ field.name }}')" value="{{ obj.id }}">{{ obj }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-lg-5">
                                    <select ele-type="right-select-ele" name="{{ field.name }}" id="{{ field.name }}_to" multiple class="form-control">
                                        {% for obj in selected_m2m_objects %}
                                            <option ondblclick="MoveElementTo(this,'{{ field.name }}_from','{{ field.name }}')"  value="{{ obj.id }}">{{ obj }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endif %}
                    <span style="color:gray;font-size: 10px">{{ field.help_text }}</span>
                    <span style="color: red">{{ field.errors.0 }}  </span>
                </div>
            </div>
            {% endif %}
            {% endfor %}

            <div class="form-group">
                <div class="col-sm-1 col-lg-offset-10">
                    <input type="submit" class="btn btn-info" value="Save" />
                </div>
            </div>
        </form>

</div>

<script>


</script>



{% endblock %}

templates/gloab-form/detail_form.html
{% extends 'bash/bash.html' %}
{% block head%}

{% endblock %}
{% block content %}
{% load deploy_tag %}
<div class="row" id="report1">
        <div class="col-sm-12">
            <ol class="breadcrumb" style="background-color: #ffffff;font-size: 10px;top: -20px">
                <a href="/" class="tip-bottom" data-original-title="Go to Home"><i class="icon-home"></i> Home </a>>
                <a href="/asset/{{ model_name }}/" class="tip-bottom" data-original-title="">{% build_project_verbose_name admin_class %}</a>>
                <a href="/asset/{{ model_name }}/" title="数据中心信息表" class="tip-bottom" data-original-title="">{% build_project_verbose_name admin_class %}信息表</a>
            </ol>
            <h4 style="text-align: center">{% build_project_verbose_name admin_class %}</h4>

        </div>
    </div>
    <div class="row" id="report1">


    </div>
<div class="row" id="report1">
    <div class="col-lg-12 class-title">
        <div class="ibox float-e-margins" id="all">

            <div class="container-fluid">
                <div class="row-fluid">
                    <form method="post" >{% csrf_token %}
                        <table class="table table-bordered ">
                            <thead>
                                <tr>
                                    {% if model_name == 'idc' %}
                                    <th class='text-center'>机柜编号</th>
                                    <th class='text-center'>机柜使用百分比(%)</th>
                                    {% elif model_name == 'cabint' %}
                                        <th class='text-center'>机柜编号</th>
                                        <th class='text-center'>设备所在位置</th>
                                        <th class='text-center'>设备名称</th>
                                        <th class='text-center'>设备IP</th>
                                        <th class='text-center'>设备高度</th>
                                    {% elif model_name == 'device' %}
                                        <th class="text-center">设备名称</th>
                                        <th class="text-center">设备IP</th>
                                        <th class="text-center">协议号</th>
                                        <th class="text-center">端口</th>
                                        <th class="text-center">服务器</th>
                                    {% elif model_name == 'servers' %}
                                        <th class="text-center">主机名</th>
                                        <th class="text-center">主机IP</th>
                                        <th class="text-center">CPU核数</th>
                                        <th class="text-center">CPU数量</th>
                                        <th class="text-center">内存</th>
                                        <th class="text-center">硬盘</th>
                                        <th class="text-center">网卡IP</th>
                                        <th class="text-center">VLAN</th>
                                        <th class="text-center">交换机</th>
                                    {% elif model_name == 'protocol' %}
                                        <th class="text-center">协议名称</th>
                                        <th class="text-center">协议号</th>
                                        <th class="text-center">IP地址</th>
                                        <th class="text-center">端口范围</th>
                                        <th class="text-center">设备</th>
                                    {% elif model_name == 'bonding' %}
                                        <th class="text-center">网卡</th>
                                        <th class="text-center">设备</th>
                                        <th class="text-center">模式</th>
                                        <th class="text-center">IP1</th>
                                        <th class="text-center">IP2</th>
                                        <th class="text-center">IP3</th>
                                        <th class="text-center">IP4</th>
                                    {% endif %}
                                </tr>

                            </thead>
                            <tbody id="tbody" class="tab-content responsive">
                                <div class="col-lg-12">
                                    {% if model_name == 'idc' %}
                                        {% build_cabint_listinfo obj obj_id%}
                                    {% elif model_name == 'cabint' %}
                                        {% build_cabint_useinfo obj obj_id%}
                                    {% elif model_name == 'device' %}
                                        {% build_device_info obj obj_id %}
                                    {% elif model_name == 'servers' %}
                                        {% build_servers_info obj obj_id %}
                                    {% elif model_name == 'protocol' %}
                                        {% build_protocol_info obj obj_id %}
                                    {% elif model_name == 'bonding' %}
                                        {% build_bonding_info obj obj_id %}
                                    {% endif %}
                                </div>
                            </tbody>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>





<script>

function all_del_file(self) {
    var check = document.getElementsByName("_selected_obj");
    var len = check.length;
    var idAll = "";
    for (var i = 0; i<len;i++){
        if(check[i].checked){
            idAll += check[i].value+',';
        }
    }
    if(idAll == ''){
        var td_id = $(this).closest('tr').find('th').eq(1).text();
        idAll = td_id + ',' ;
    }
    console.log('idall',idAll);
    $.ajax({
        url:"/asset/{{ app_name }}/{{ model_name }}/del/?idAll=" + idAll,
        type: 'post',
        success:function (data) {
            alert('删除成功',data);
            location.reload(true)
        }
    })
}


function checkAll(self) {
    if ( $(self).prop('checked')){

        $("table .row-obj").prop('checked',true)
    }else {
         $("table .row-obj").prop('checked',false)
    }

}

</script>
{% endblock %}